### ISSUE TITLE
Para Rosario?

### ISSUE THREAD

**Issue by MRacciatti** [Aguss-Coder/Prenotami-Scrapper#1]
Hola loco... una pregunta: Sirve para el consulado de rosario? Y en qué consiste aparte de logearte? Gracias.

**Comment by agusslud** [comment]
Hola, el scrapper funciona para la pagina de Prenotami sin importar que consulado este elegido, por ahora el proyecto solamente inicia sesión y se mantiene buscando algún turno el día que se habilite o lo podes dejar buscando turnos fantasma (son turnos que se cancelaron y volvieron a estar disponible), pero no hace mas que eso, la parte de llenar los datos para poder conseguir el turno lo tenes que hacer vos.

**Comment by MRacciatti** [comment]
> Hola, el scrapper funciona para la pagina de Prenotami sin importar que consulado este elegido, por ahora el proyecto solamente inicia sesión y se mantiene buscando algún turno el día que se habilite o lo podes dejar buscando turnos fantasma (son turnos que se cancelaron y volvieron a estar disponible), pero no hace mas que eso, la parte de llenar los datos para poder conseguir el turno lo tenes que hacer vos.

Gracias por contestar crack. Si, eso yo también lo hice con ayuda de chatgpt. Busca turnos que hayan sido cancelados y cuando detecta que hay alguno disponible me manda un alerta a telegram. Servir sirve aunque aún no encontró ninguno disponible. Si me interesa algún código que sea para completar los formularios automáticamente cuando encuentre el turno. Ya lo voy a intentar hacer.
